/**
 * Generates a standalone React component for a single slide.
 * The output is a self-contained .tsx file that can live in the repo.
 */

import type {
  Placeholder,
  SlideLayout,
  SlideTheme,
} from "@/parser/pptxParser";

export interface SlideCodeInput {
  componentName: string;
  layout: SlideLayout;
  theme: SlideTheme;
  content: Record<string, string>;
}

function indent(text: string, level: number): string {
  const pad = "  ".repeat(level);
  return text
    .split("\n")
    .map((l) => (l.trim() ? pad + l : l))
    .join("\n");
}

function escapeJsx(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/`/g, "\\`");
}

function buildPlaceholderJsx(
  p: Placeholder,
  content: Record<string, string>,
): string {
  const text = content[String(p.idx)] || "";
  const escaped = escapeJsx(text);

  const wrapperStyle = [
    `position: "absolute"`,
    `left: "${p.position.x}%"`,
    `top: "${p.position.y}%"`,
    `width: "${p.position.w}%"`,
    `height: "${p.position.h}%"`,
    `padding: "4px"`,
    `display: "flex"`,
    `alignItems: "flex-start"`,
    `overflow: "hidden"`,
  ].join(", ");

  let inner = "";
  switch (p.type) {
    case "title":
    case "ctrTitle":
      inner = `<p style={{ fontFamily: "var(--slide-font-heading)", color: "var(--slide-primary)", fontSize: "clamp(20px, 3.2vw, 42px)", fontWeight: 700, lineHeight: 1.2, margin: 0 }}>{"${escaped}"}</p>`;
      break;
    case "subTitle":
      inner = `<p style={{ fontFamily: "var(--slide-font-body)", color: "var(--slide-text-muted)", fontSize: "clamp(13px, 1.8vw, 24px)", lineHeight: 1.4, margin: 0 }}>{"${escaped}"}</p>`;
      break;
    case "body":
      inner = `<div style={{ fontFamily: "var(--slide-font-body)", color: "var(--slide-text)", fontSize: "clamp(11px, 1.4vw, 18px)", lineHeight: 1.6, whiteSpace: "pre-line" }}>{"${escaped}"}</div>`;
      break;
    default:
      inner = `<p style={{ fontFamily: "var(--slide-font-body)", color: "var(--slide-text-muted)", fontSize: "11px", margin: 0 }}>{"${escaped}"}</p>`;
  }

  return `      {/* ${p.type}:${p.idx} */}\n      <div style={{ ${wrapperStyle} }}>\n        ${inner}\n      </div>`;
}

export function generateSlideCode(input: SlideCodeInput): string {
  const { componentName, layout, theme, content } = input;

  const cssVarEntries = Object.entries(theme.cssVars)
    .map(([k, v]) => `    "${k}": "${v}"`)
    .join(",\n");

  const placeholderBlocks = layout.placeholders
    .map((p) => buildPlaceholderJsx(p, content))
    .join("\n\n");

  return `import React from "react";

/**
 * Auto-generated slide component.
 * Layout: "${layout.name}"
 * Generated by SlideForge.
 */

const THEME_VARS: React.CSSProperties = {
${cssVarEntries},
} as React.CSSProperties;

const ${componentName}: React.FC = () => {
  return (
    <div
      style={{
        width: 1280,
        height: 720,
        position: "relative",
        overflow: "hidden",
        background: "var(--slide-bg)",
        ...THEME_VARS,
      }}
    >
${placeholderBlocks}
    </div>
  );
};

export default ${componentName};
`;
}

/**
 * Suggest a file path for the generated component based on project + folder structure.
 */
export function suggestFilePath(
  projectName: string,
  folderPath: string,
  componentName: string,
): string {
  const base = "src/slides";
  const clean = (s: string) =>
    s
      .replace(/[^a-zA-Z0-9äöüÄÖÜß\-_ ]/g, "")
      .replace(/\s+/g, "-")
      .toLowerCase();
  const parts = [base];
  if (projectName) parts.push(clean(projectName));
  if (folderPath) parts.push(clean(folderPath));
  parts.push(`${componentName}.tsx`);
  return parts.join("/");
}
